# Generated by Django 6.0.6 on 2026-07-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_over_per_innings'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('LEAGUE', 'League'), ('QUALIFIER_1', 'Qualifier 1'), ('ELIMINATOR', 'Eliminator'), ('QUALIFIER_2', 'Oualifier 2'), ('FINAL', 'Final')], default='LEAGUE', max_length=15),
        ),
    ]
