# Generated by Django 6.0.6 on 2026-07-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('city', models.CharField(max_length=80)),
                ('venue', models.CharField(blank=True, max_length=150)),
                ('format', models.CharField(choices=[('T10', 'T10'), ('T20', 'T20'), ('ODI', 'One Day'), ('CUSTOM', 'Custom')], default='T20', max_length=10)),
                ('over_per_innings', models.PositiveSmallIntegerField(default=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teams', models.ManyToManyField(blank=True, related_name='tournaments', to='teams.team')),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
    ]
