# Generated by Django 6.0.6 on 2026-07-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='competition_type',
            field=models.CharField(choices=[('NORMAL', 'Normal Tournament'), ('PREMIER_LEAGUE', 'Premier League')], default='NORMAL', max_length=20),
        ),
    ]
