# Generated by Django 6.0.6 on 2026-07-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_competition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='over_per_innings',
            field=models.PositiveSmallIntegerField(default=6),
        ),
    ]
