# Generated by Django 6.0.6 on 2026-07-16 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0003_match_stage'),
        ('players', '0002_alter_player_bowling_style'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Innings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='1 for the first innings, 2 for the second innings.')),
                ('target_runs', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_innings', to='teams.team')),
                ('bowling_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bowing_innings', to='teams.team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings', to='matches.match')),
            ],
            options={
                'ordering': ['match', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='Order of this delivery in the innings.')),
                ('runs_off_bat', models.PositiveSmallIntegerField(default=0)),
                ('extras', models.PositiveSmallIntegerField(default=0)),
                ('extra_type', models.CharField(choices=[('NONE', 'No extra'), ('WIDE', 'Wide'), ('NO_BALL', 'No ball'), ('BYE', 'Bye'), ('LEG_BYE', 'Leg bye'), ('PENALTY', 'Penalty')], default='NONE', max_length=10)),
                ('is_legal_delivery', models.BooleanField(default=True)),
                ('is_wicket', models.BooleanField(default=False)),
                ('dismissal_kind', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bowled_deliveries', to='players.player')),
                ('non_striker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='non_striker_deliveries', to='players.player')),
                ('striker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faced_deliveries', to='players.player')),
                ('wicket_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dismissals', to='players.player')),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='scoring.innings')),
            ],
            options={
                'ordering': (['innings', 'sequence'],),
            },
        ),
        migrations.AddConstraint(
            model_name='innings',
            constraint=models.UniqueConstraint(fields=('match', 'number'), name='unique_innings_number_per_match'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('innings', 'sequence'), name='unique_delivery_sequence_per_innings'),
        ),
    ]
