# Generated by Django 6.0.6 on 2026-07-17 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_bowling_style'),
        ('scoring', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['inning', 'sequence']},
        ),
        migrations.RemoveConstraint(
            model_name='delivery',
            name='unique_delivery_sequence_per_innings',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='innings',
            new_name='inning',
        ),
        migrations.AlterField(
            model_name='innings',
            name='batting_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batting_innings', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='innings',
            name='bowling_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bowling_innings', to='teams.team'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('inning', 'sequence'), name='unique_delivery_sequence_per_inning'),
        ),
    ]
