# Generated by Django 6.0.6 on 2026-07-21 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_bowling_style'),
        ('scoring', '0002_alter_delivery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='innings',
            name='current_bowler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currently_bowling', to='players.player'),
        ),
        migrations.AddField(
            model_name='innings',
            name='current_non_striker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currently_non_striking', to='players.player'),
        ),
        migrations.AddField(
            model_name='innings',
            name='current_striker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currently_striking', to='players.player'),
        ),
        migrations.AddField(
            model_name='innings',
            name='needs_new_bowler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='innings',
            name='opening_Striker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_as_striker', to='players.player'),
        ),
        migrations.AddField(
            model_name='innings',
            name='opening_non_striker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_as_non_striker', to='players.player'),
        ),
    ]
