# Generated by Django 6.0.6 on 2026-07-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('batting_style', models.CharField(choices=[('RIGHT', 'Right-hand bat'), ('LEFT', 'Left-hand bat')], default='RIGHT', max_length=10)),
                ('bowling_style', models.CharField(choices=[('NONE', 'Dose not bowl'), ('PACE', 'Fast / Medium pace'), ('OFF_SPIN', 'Off spin'), ('LEG_SPIN', 'let-spin'), ('LEFT_ARM', 'Left-arm spin')], default='NONE', max_length=15)),
                ('is_wicketkeeper', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
