# Generated by Django 6.0.6 on 2026-07-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bowling_style',
            field=models.CharField(choices=[('NONE', 'Dose not bowl'), ('PACE', 'Fast / Medium pace'), ('OFF_SPIN', 'Off spin'), ('LEG_SPIN', 'leg-spin'), ('LEFT_ARM', 'Left-arm spin')], default='NONE', max_length=15),
        ),
    ]
