# Generated by Django 6.0.6 on 2026-09-05 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_bowling_style'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='player',
            name='bowling_style',
            field=models.CharField(choices=[('NONE', 'Does not bowl'), ('PACE', 'Fast / Medium pace'), ('OFF_SPIN', 'Off spin'), ('LEG_SPIN', 'leg-spin'), ('LEFT_ARM', 'Left-arm spin')], default='NONE', max_length=15),
        ),
    ]
