# Generated by Django 6.0.6 on 2026-09-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_user_alter_player_bowling_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='player_photos/'),
        ),
    ]
